/********************************************************************
 * capteur_tor.h
 * 
 * generated by: plcgen 1.0.30
 * generation parameters:
 *  -L C:\controlbuild\tooldir\embedded\nt_simu\embedded
 *  --fl iec_1131
 *  --nl
 *  -R C:\temp\TP_1_TAPI
 *  -c
 *  tapis_conv.capteur_tor
 ********************************************************************/

#ifndef _TAPIS_CONV__CAPTEUR_TOR_H
#define _TAPIS_CONV__CAPTEUR_TOR_H


/********************** Variable declarations ***********************/

extern CB_Index capteur_tor__num;
extern CB_Mem_Float *capteur_tor_Position_IN;
extern CB_Mem_Float *capteur_tor_Position_Fixe;
extern CB_Mem_Bool *capteur_tor_Etat;
extern CB_Mem_Float *capteur_tor_Fourchette;

/********************** Function declarations ***********************/

extern int tapis_conv__capteur_tor_init(void);
extern int tapis_conv__capteur_tor(void);

#endif /*_TAPIS_CONV__CAPTEUR_TOR_H*/
