/********************************************************************
 * capteur_tor.c
 * 
 * generated by: plcgen 1.0.30
 * generation parameters:
 *  -L C:\controlbuild\tooldir\embedded\nt_simu\embedded
 *  --fl iec_1131
 *  --nl
 *  -R C:\temp\TP_1_TAPI
 *  -c
 *  tapis_conv.capteur_tor
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "capteur_tor.h"


/**************************** Variables *****************************/

CB_Index capteur_tor__num = 0;
CB_Mem_Float *capteur_tor_Position_IN;
CB_Mem_Float *capteur_tor_Position_Fixe;
CB_Mem_Bool *capteur_tor_Etat;
CB_Mem_Float *capteur_tor_Fourchette;
#define COUR(v) (capteur_tor_##v->CB_current_value)
#define FIGE(v) (capteur_tor_##v->CB_previous_value)
#define RE(v) (capteur_tor_##v->CB_positive_edge)
#define FE(v) (capteur_tor_##v->CB_negative_edge)
#define _RE(v) (capteur_tor_##v->CB_current_value > capteur_tor_##v->CB_previous_value)
#define _FE(v) (capteur_tor_##v->CB_current_value < capteur_tor_##v->CB_previous_value)
#define FM(v) (capteur_tor_##v->CB_positive_edge)
#define FD(v) (capteur_tor_##v->CB_negative_edge)


/**************************** Variables *****************************/

#define Position_IN (capteur_tor_Position_IN->CB_previous_value)
#define Position_Fixe (capteur_tor_Position_Fixe->CB_previous_value)
#define Etat (capteur_tor_Etat->CB_current_value)
#define Fourchette (capteur_tor_Fourchette->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

int tapis_conv__capteur_tor_init(void)
{
	(self.Float+0)->CB_current_value = 0.1; /*Fourchette*/
	self.Float+=1;


	return 0;
}


/************************ Behavior function *************************/

int tapis_conv__capteur_tor(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/

		capteur_tor_Fourchette = self.Float+0;

		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			if (Position_IN > Position_Fixe - Fourchette && Position_IN < Position_Fixe + Fourchette) {
				Etat = 1;
			}
			else {
				Etat = 0;
			}
		}

		if(withoutDelay) {
			CB_freeze_bool(capteur_tor_Etat);
		}

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Float += 1;

	return 0;
}

