/********************************************************************
 * stockage.h
 * 
 * generated by: plcgen 1.0.30
 * generation parameters:
 *  -L C:\controlbuild\tooldir\embedded\nt_simu\embedded
 *  --fl iec_1131
 *  --nl
 *  -R C:\temp\TP_1_TAPI
 *  -c
 *  tapis_conv.stockage
 ********************************************************************/

#ifndef _TAPIS_CONV__STOCKAGE_H
#define _TAPIS_CONV__STOCKAGE_H


/********************** Variable declarations ***********************/

extern CB_Index stockage__num;
extern CB_Mem_Bool *stockage_In;
extern CB_Mem_Bool *stockage_Out;
extern CB_Mem_Int *stockage_Nb_Pieces;

/********************** Function declarations ***********************/

extern int tapis_conv__stockage_init(void);
extern int tapis_conv__stockage(void);

#endif /*_TAPIS_CONV__STOCKAGE_H*/
