/********************************************************************
 * stockage.c
 * 
 * generated by: plcgen 1.0.30
 * generation parameters:
 *  -L C:\controlbuild\tooldir\embedded\nt_simu\embedded
 *  --fl iec_1131
 *  --nl
 *  -R C:\temp\TP_1_TAPI
 *  -c
 *  tapis_conv.stockage
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "stockage.h"


/**************************** Variables *****************************/

CB_Index stockage__num = 0;
CB_Mem_Bool *stockage_In;
CB_Mem_Bool *stockage_Out;
CB_Mem_Int *stockage_Nb_Pieces;
#define COUR(v) (stockage_##v->CB_current_value)
#define FIGE(v) (stockage_##v->CB_previous_value)
#define RE(v) (stockage_##v->CB_positive_edge)
#define FE(v) (stockage_##v->CB_negative_edge)
#define _RE(v) (stockage_##v->CB_current_value > stockage_##v->CB_previous_value)
#define _FE(v) (stockage_##v->CB_current_value < stockage_##v->CB_previous_value)
#define FM(v) (stockage_##v->CB_positive_edge)
#define FD(v) (stockage_##v->CB_negative_edge)


/**************************** Variables *****************************/

#define In (stockage_In->CB_previous_value)
#define Out (stockage_Out->CB_previous_value)
#define Nb_Pieces (*((short *)&(stockage_Nb_Pieces->CB_current_value) + ALIGN_OFFSET_SHORT))


/************************ Components offsets ************************/


/********************* Initialization function **********************/

int tapis_conv__stockage_init(void)
{


	return 0;
}


/************************ Behavior function *************************/

int tapis_conv__stockage(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/


		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			if (In == 1) {
				Nb_Pieces = Nb_Pieces + 1;
			}
			if (Out == 1) {
				Nb_Pieces = Nb_Pieces - 1;
			}
		}

		if(withoutDelay) {
			CB_freeze_int(stockage_Nb_Pieces);
		}

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/


	return 0;
}

