/********************************************************************
 * tapis_conv.c
 * 
 * generated by: plcgen 1.0.30
 * generation parameters:
 *  -L C:\controlbuild\tooldir\embedded\nt_simu\embedded
 *  --fl iec_1131
 *  --nl
 *  -p
 *  -R P:\RI\TP_1_TAPI
 *  -c
 *  tapis_conv.tapis_conv
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "tapis_conv.h"
#include "tapis_conv/functional/po/exec/po.h"
#include "tapis_conv/functional/pc/exec/pc.h"


/**************************** Variables *****************************/

CB_Index tapis_conv__num = 0;
#define COUR(v) (tapis_conv_##v->CB_current_value)
#define FIGE(v) (tapis_conv_##v->CB_previous_value)
#define RE(v) (tapis_conv_##v->CB_positive_edge)
#define FE(v) (tapis_conv_##v->CB_negative_edge)
#define _RE(v) (tapis_conv_##v->CB_current_value > tapis_conv_##v->CB_previous_value)
#define _FE(v) (tapis_conv_##v->CB_current_value < tapis_conv_##v->CB_previous_value)
#define FM(v) (tapis_conv_##v->CB_positive_edge)
#define FD(v) (tapis_conv_##v->CB_negative_edge)


/**************************** Variables *****************************/



/************************ Components offsets ************************/

static CB_Offset tapis_conv__tapis_conv_offset_po1;
static CB_Offset tapis_conv__tapis_conv_offset_pc1;
static CB_Offset tapis_conv__tapis_conv_offset__end = {0, 0, 0, 0};


/********************* Initialization function **********************/

int tapis_conv__tapis_conv_init(void)
{
	CB_Object __start = self;
	self.Bool+=4;

	/*initialize child po1 (tapis_conv.po):*/
	tapis_conv__tapis_conv_offset_po1.Bool = self.Bool - __start.Bool;
	tapis_conv__tapis_conv_offset_po1.Int = self.Int - __start.Int;
	tapis_conv__tapis_conv_offset_po1.Float = self.Float - __start.Float;
	tapis_conv__tapis_conv_offset_po1.Char = self.Char - __start.Char;
	tapis_conv__po_init();

	/*initialize child pc1 (tapis_conv.pc):*/
	tapis_conv__tapis_conv_offset_pc1.Bool = self.Bool - __start.Bool;
	tapis_conv__tapis_conv_offset_pc1.Int = self.Int - __start.Int;
	tapis_conv__tapis_conv_offset_pc1.Float = self.Float - __start.Float;
	tapis_conv__tapis_conv_offset_pc1.Char = self.Char - __start.Char;
	pc_Fin_Convoyage = __start.Bool+3; /*tapis_conv__cn_1*/
	pc_Chargement = __start.Bool+2; /*tapis_conv__cn_2*/
	pc_Dechargement = __start.Bool+1; /*tapis_conv__cn_3*/
	pc_Marche = __start.Bool+0; /*tapis_conv__cn_4*/
	tapis_conv__pc_init();

	tapis_conv__tapis_conv_offset__end.Bool = self.Bool - __start.Bool;
	tapis_conv__tapis_conv_offset__end.Int = self.Int - __start.Int;
	tapis_conv__tapis_conv_offset__end.Float = self.Float - __start.Float;
	tapis_conv__tapis_conv_offset__end.Char = self.Char - __start.Char;

	return 0;
}


/************************ Behavior function *************************/

int tapis_conv__tapis_conv(void)
{
	CB_Object __start = self;
	int __ret;
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/

								
		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			self.Bool = __start.Bool + tapis_conv__tapis_conv_offset_po1.Bool;
			self.Int = __start.Int + tapis_conv__tapis_conv_offset_po1.Int;
			self.Float = __start.Float + tapis_conv__tapis_conv_offset_po1.Float;
			self.Char = __start.Char + tapis_conv__tapis_conv_offset_po1.Char;

			/************************** po1 execution ***************************/

			self_num++;
			if (po__num != self_num) {
				po__num = self_num;
			}
			__ret = tapis_conv__po();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/************************** pc1 execution ***************************/

			self_num++;
			if (pc__num != self_num) {
				pc__num = self_num;
				pc_Fin_Convoyage = __start.Bool+3; /*tapis_conv__cn_1*/
				pc_Chargement = __start.Bool+2; /*tapis_conv__cn_2*/
				pc_Dechargement = __start.Bool+1; /*tapis_conv__cn_3*/
				pc_Marche = __start.Bool+0; /*tapis_conv__cn_4*/
			}
			__ret = tapis_conv__pc();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool = __start.Bool + tapis_conv__tapis_conv_offset__end.Bool;
	self.Int = __start.Int + tapis_conv__tapis_conv_offset__end.Int;
	self.Float = __start.Float + tapis_conv__tapis_conv_offset__end.Float;
	self.Char = __start.Char + tapis_conv__tapis_conv_offset__end.Char;

	return 0;
}

