/********************************************************************
 * tapis_conv.h
 * 
 * generated by: plcgen 1.0.30
 * generation parameters:
 *  -L C:\controlbuild\tooldir\embedded\nt_simu\embedded
 *  --fl iec_1131
 *  --nl
 *  -p
 *  -R P:\RI\TP_1_TAPI
 *  -c
 *  tapis_conv.tapis_conv
 ********************************************************************/

#ifndef _TAPIS_CONV__TAPIS_CONV_H
#define _TAPIS_CONV__TAPIS_CONV_H


/********************** Variable declarations ***********************/

extern CB_Index tapis_conv__num;

/********************** Function declarations ***********************/

extern int tapis_conv__tapis_conv_init(void);
extern int tapis_conv__tapis_conv(void);

#endif /*_TAPIS_CONV__TAPIS_CONV_H*/
