/********************************************************************
 * pc.c
 * 
 * generated by: plcgen 1.0.30
 * generation parameters:
 *  -L C:\controlbuild\tooldir\embedded\nt_simu\embedded
 *  --fl iec_1131
 *  --nl
 *  -p
 *  -R C:\temp\TP_1_TAPI
 *  -c
 *  tapis_conv.pc
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "pc.h"
#include "tapis_conv/functional/graf/exec/graf.h"


/**************************** Variables *****************************/

CB_Index pc__num = 0;
CB_Mem_Bool *pc_Fin_Convoyage;
CB_Mem_Bool *pc_Chargement;
CB_Mem_Bool *pc_Dechargement;
CB_Mem_Bool *pc_Marche;
#define COUR(v) (pc_##v->CB_current_value)
#define FIGE(v) (pc_##v->CB_previous_value)
#define RE(v) (pc_##v->CB_positive_edge)
#define FE(v) (pc_##v->CB_negative_edge)
#define _RE(v) (pc_##v->CB_current_value > pc_##v->CB_previous_value)
#define _FE(v) (pc_##v->CB_current_value < pc_##v->CB_previous_value)
#define FM(v) (pc_##v->CB_positive_edge)
#define FD(v) (pc_##v->CB_negative_edge)


/**************************** Variables *****************************/



/************************ Components offsets ************************/

static CB_Offset tapis_conv__pc_offset_graf1;
static CB_Offset tapis_conv__pc_offset__end = {0, 0, 0, 0};


/********************* Initialization function **********************/

int tapis_conv__pc_init(void)
{
	CB_Object __start = self;

	/*initialize child graf1 (tapis_conv.graf):*/
	tapis_conv__pc_offset_graf1.Bool = self.Bool - __start.Bool;
	tapis_conv__pc_offset_graf1.Int = self.Int - __start.Int;
	tapis_conv__pc_offset_graf1.Float = self.Float - __start.Float;
	tapis_conv__pc_offset_graf1.Char = self.Char - __start.Char;
	graf_Fin_Convoyage = pc_Fin_Convoyage;
	graf_Chargement = pc_Chargement;
	graf_Dechargement = pc_Dechargement;
	graf_Marche = pc_Marche;
	tapis_conv__graf_init();

	tapis_conv__pc_offset__end.Bool = self.Bool - __start.Bool;
	tapis_conv__pc_offset__end.Int = self.Int - __start.Int;
	tapis_conv__pc_offset__end.Float = self.Float - __start.Float;
	tapis_conv__pc_offset__end.Char = self.Char - __start.Char;

	return 0;
}


/************************ Behavior function *************************/

int tapis_conv__pc(void)
{
	CB_Object __start = self;
	int __ret;
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/


		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			self.Bool = __start.Bool + tapis_conv__pc_offset_graf1.Bool;
			self.Int = __start.Int + tapis_conv__pc_offset_graf1.Int;
			self.Float = __start.Float + tapis_conv__pc_offset_graf1.Float;
			self.Char = __start.Char + tapis_conv__pc_offset_graf1.Char;

			/************************* graf1 execution **************************/

			self_num++;
			if (graf__num != self_num) {
				graf__num = self_num;
				graf_Fin_Convoyage = pc_Fin_Convoyage;
				graf_Chargement = pc_Chargement;
				graf_Dechargement = pc_Dechargement;
				graf_Marche = pc_Marche;
			}
			__ret = tapis_conv__graf();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool = __start.Bool + tapis_conv__pc_offset__end.Bool;
	self.Int = __start.Int + tapis_conv__pc_offset__end.Int;
	self.Float = __start.Float + tapis_conv__pc_offset__end.Float;
	self.Char = __start.Char + tapis_conv__pc_offset__end.Char;

	return 0;
}

