/********************************************************************
 * pc.h
 * 
 * generated by: plcgen 1.0.30
 * generation parameters:
 *  -L C:\controlbuild\tooldir\embedded\nt_simu\embedded
 *  --fl iec_1131
 *  --nl
 *  -p
 *  -R C:\temp\TP_1_TAPI
 *  -c
 *  tapis_conv.pc
 ********************************************************************/

#ifndef _TAPIS_CONV__PC_H
#define _TAPIS_CONV__PC_H


/********************** Variable declarations ***********************/

extern CB_Index pc__num;
extern CB_Mem_Bool *pc_Fin_Convoyage;
extern CB_Mem_Bool *pc_Chargement;
extern CB_Mem_Bool *pc_Dechargement;
extern CB_Mem_Bool *pc_Marche;

/********************** Function declarations ***********************/

extern int tapis_conv__pc_init(void);
extern int tapis_conv__pc(void);

#endif /*_TAPIS_CONV__PC_H*/
