/********************************************************************
 * _init.h
 * 
 * generated by: plcgen 1.0.30
 * generation parameters:
 *  -L C:\controlbuild\tooldir\embedded\nt_simu\embedded
 *  --fl iec_1131
 *  --nl
 *  -R C:\temp\TP_1_TAPI
 *  tapis_conv.po
 ********************************************************************/

#define mx_use_tapis_conv__tapis
#define mx_use_tapis_conv__stockage
#define mx_use_tapis_conv__capteur_tor
#define mx_use_tapis_conv__po


