/********************************************************************
 * po.c
 * 
 * generated by: plcgen 1.0.30
 * generation parameters:
 *  -L C:\controlbuild\tooldir\embedded\nt_simu\embedded
 *  --fl iec_1131
 *  --nl
 *  -p
 *  -R C:\temp\TP_1_TAPI
 *  -c
 *  tapis_conv.po
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "po.h"
#include "tapis_conv/functional/tapis/exec/tapis.h"
#include "tapis_conv/functional/stockage/exec/stockage.h"
#include "tapis_conv/functional/capteur_tor/exec/capteur_tor.h"


/**************************** Variables *****************************/

CB_Index po__num = 0;
CB_Mem_Bool *po_Marche;
CB_Mem_Bool *po_Chargement;
CB_Mem_Bool *po_Dechargement;
CB_Mem_Bool *po_Fin_Convoyage;
#define COUR(v) (po_##v->CB_current_value)
#define FIGE(v) (po_##v->CB_previous_value)
#define RE(v) (po_##v->CB_positive_edge)
#define FE(v) (po_##v->CB_negative_edge)
#define _RE(v) (po_##v->CB_current_value > po_##v->CB_previous_value)
#define _FE(v) (po_##v->CB_current_value < po_##v->CB_previous_value)
#define FM(v) (po_##v->CB_positive_edge)
#define FD(v) (po_##v->CB_negative_edge)


/**************************** Variables *****************************/



/************************ Components offsets ************************/

static CB_Offset tapis_conv__po_offset_tapis1;
static CB_Offset tapis_conv__po_offset_stockage1;
static CB_Offset tapis_conv__po_offset_capteur_tor1;
static CB_Offset tapis_conv__po_offset__end = {0, 0, 0, 0};


/********************* Initialization function **********************/

int tapis_conv__po_init(void)
{
	CB_Object __start = self;
	self.Int+=1;
	self.Float+=2;

	/*initialize child tapis1 (tapis_conv.tapis):*/
	tapis_conv__po_offset_tapis1.Bool = self.Bool - __start.Bool;
	tapis_conv__po_offset_tapis1.Int = self.Int - __start.Int;
	tapis_conv__po_offset_tapis1.Float = self.Float - __start.Float;
	tapis_conv__po_offset_tapis1.Char = self.Char - __start.Char;
	tapis_Marche = po_Marche;
	tapis_Deplacement = __start.Float+1; /*po__cn_1*/
	tapis_conv__tapis_init();

	/*initialize child stockage1 (tapis_conv.stockage):*/
	tapis_conv__po_offset_stockage1.Bool = self.Bool - __start.Bool;
	tapis_conv__po_offset_stockage1.Int = self.Int - __start.Int;
	tapis_conv__po_offset_stockage1.Float = self.Float - __start.Float;
	tapis_conv__po_offset_stockage1.Char = self.Char - __start.Char;
	stockage_In = po_Chargement;
	stockage_Out = po_Dechargement;
	stockage_Nb_Pieces = __start.Int+0; /*po__cn_2*/
	tapis_conv__stockage_init();

	/*initialize child capteur_tor1 (tapis_conv.capteur_tor):*/
	tapis_conv__po_offset_capteur_tor1.Bool = self.Bool - __start.Bool;
	tapis_conv__po_offset_capteur_tor1.Int = self.Int - __start.Int;
	tapis_conv__po_offset_capteur_tor1.Float = self.Float - __start.Float;
	tapis_conv__po_offset_capteur_tor1.Char = self.Char - __start.Char;
	capteur_tor_Position_IN = __start.Float+1; /*po__cn_1*/
	capteur_tor_Position_Fixe = __start.Float+0; /*po__cn_3*/
	capteur_tor_Etat = po_Fin_Convoyage;
	tapis_conv__capteur_tor_init();

	tapis_conv__po_offset__end.Bool = self.Bool - __start.Bool;
	tapis_conv__po_offset__end.Int = self.Int - __start.Int;
	tapis_conv__po_offset__end.Float = self.Float - __start.Float;
	tapis_conv__po_offset__end.Char = self.Char - __start.Char;

	return 0;
}


/************************ Behavior function *************************/

int tapis_conv__po(void)
{
	CB_Object __start = self;
	int __ret;
	if (exec_mac_node(self_num)) {

		/*********************** Internals variables ************************/

						
		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			self.Bool = __start.Bool + tapis_conv__po_offset_tapis1.Bool;
			self.Int = __start.Int + tapis_conv__po_offset_tapis1.Int;
			self.Float = __start.Float + tapis_conv__po_offset_tapis1.Float;
			self.Char = __start.Char + tapis_conv__po_offset_tapis1.Char;

			/************************* tapis1 execution *************************/

			self_num++;
			if (tapis__num != self_num) {
				tapis__num = self_num;
				tapis_Marche = po_Marche;
				tapis_Deplacement = __start.Float+1; /*po__cn_1*/
			}
			__ret = tapis_conv__tapis();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/*********************** stockage1 execution ************************/

			self_num++;
			if (stockage__num != self_num) {
				stockage__num = self_num;
				stockage_In = po_Chargement;
				stockage_Out = po_Dechargement;
				stockage_Nb_Pieces = __start.Int+0; /*po__cn_2*/
			}
			__ret = tapis_conv__stockage();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

			/********************** capteur_tor1 execution **********************/

			self_num++;
			if (capteur_tor__num != self_num) {
				capteur_tor__num = self_num;
				capteur_tor_Position_IN = __start.Float+1; /*po__cn_1*/
				capteur_tor_Position_Fixe = __start.Float+0; /*po__cn_3*/
				capteur_tor_Etat = po_Fin_Convoyage;
			}
			__ret = tapis_conv__capteur_tor();
			if (__ret != 0) {
				return __ret; /*child execution failure*/
			}

		}


		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/

	self.Bool = __start.Bool + tapis_conv__po_offset__end.Bool;
	self.Int = __start.Int + tapis_conv__po_offset__end.Int;
	self.Float = __start.Float + tapis_conv__po_offset__end.Float;
	self.Char = __start.Char + tapis_conv__po_offset__end.Char;

	return 0;
}

