/********************************************************************
 * po.h
 * 
 * generated by: plcgen 1.0.30
 * generation parameters:
 *  -L C:\controlbuild\tooldir\embedded\nt_simu\embedded
 *  --fl iec_1131
 *  --nl
 *  -p
 *  -R C:\temp\TP_1_TAPI
 *  -c
 *  tapis_conv.po
 ********************************************************************/

#ifndef _TAPIS_CONV__PO_H
#define _TAPIS_CONV__PO_H


/********************** Variable declarations ***********************/

extern CB_Index po__num;
extern CB_Mem_Bool *po_Marche;
extern CB_Mem_Bool *po_Chargement;
extern CB_Mem_Bool *po_Dechargement;
extern CB_Mem_Bool *po_Fin_Convoyage;

/********************** Function declarations ***********************/

extern int tapis_conv__po_init(void);
extern int tapis_conv__po(void);

#endif /*_TAPIS_CONV__PO_H*/
