/********************************************************************
 * graf.h
 * 
 * generated by: plcgen 1.0.30
 * generation parameters:
 *  -L C:\controlbuild\tooldir\embedded\nt_simu\embedded
 *  --fl iec_1131
 *  --nl
 *  -R C:\temp\TP_1_TAPI
 *  -c
 *  tapis_conv.graf
 ********************************************************************/

#ifndef _TAPIS_CONV__GRAF_H
#define _TAPIS_CONV__GRAF_H


/********************** Variable declarations ***********************/

extern CB_Index graf__num;
extern CB_Mem_Bool *graf_Fin_Convoyage;
extern CB_Mem_Bool *graf_Chargement;
extern CB_Mem_Bool *graf_Dechargement;
extern CB_Mem_Bool *graf_Marche;
extern CB_Mem_Int *graf_nb_piece;

/********************** Function declarations ***********************/

extern int tapis_conv__graf_init(void);
extern int tapis_conv__graf(void);

#endif /*_TAPIS_CONV__GRAF_H*/
