/********************************************************************
 * tapis.c
 * 
 * generated by: plcgen 1.0.30
 * generation parameters:
 *  -L C:\controlbuild\tooldir\embedded\nt_simu\embedded
 *  --fl iec_1131
 *  --nl
 *  -R C:\temp\TP_1_TAPI
 *  -c
 *  tapis_conv.tapis
 ********************************************************************/

#include "cb_comp.h"
#include "iec_1131.h"

#include "tapis.h"


/**************************** Variables *****************************/

CB_Index tapis__num = 0;
CB_Mem_Bool *tapis_Marche;
CB_Mem_Float *tapis_Deplacement;
#define COUR(v) (tapis_##v->CB_current_value)
#define FIGE(v) (tapis_##v->CB_previous_value)
#define RE(v) (tapis_##v->CB_positive_edge)
#define FE(v) (tapis_##v->CB_negative_edge)
#define _RE(v) (tapis_##v->CB_current_value > tapis_##v->CB_previous_value)
#define _FE(v) (tapis_##v->CB_current_value < tapis_##v->CB_previous_value)
#define FM(v) (tapis_##v->CB_positive_edge)
#define FD(v) (tapis_##v->CB_negative_edge)


/**************************** Variables *****************************/

#define Marche (tapis_Marche->CB_previous_value)
#define Deplacement (tapis_Deplacement->CB_current_value)


/************************ Components offsets ************************/


/********************* Initialization function **********************/

int tapis_conv__tapis_init(void)
{


	return 0;
}


/************************ Behavior function *************************/

int tapis_conv__tapis(void)
{
	if (exec_term_node(self_num)) {

		/*********************** Internals variables ************************/


		/********************* Pre-conditions execution *********************/

		/*no Pre-conditions*/

		/************************ Behavior execution ************************/

		{
			if (Marche == 1) {
				while (Deplacement < 50) {
					Deplacement = Deplacement + 0.1;
					break;
				}
			}
		}

		if(withoutDelay) {
			CB_freeze_float(tapis_Deplacement);
		}

		/******************** Post-conditions execution *********************/

		/*no Post-conditions*/
	}

	/*************************** self update ****************************/


	return 0;
}

