/********************************************************************
 * tapis.h
 * 
 * generated by: plcgen 1.0.30
 * generation parameters:
 *  -L C:\controlbuild\tooldir\embedded\nt_simu\embedded
 *  --fl iec_1131
 *  --nl
 *  -R C:\temp\TP_1_TAPI
 *  -c
 *  tapis_conv.tapis
 ********************************************************************/

#ifndef _TAPIS_CONV__TAPIS_H
#define _TAPIS_CONV__TAPIS_H


/********************** Variable declarations ***********************/

extern CB_Index tapis__num;
extern CB_Mem_Bool *tapis_Marche;
extern CB_Mem_Float *tapis_Deplacement;

/********************** Function declarations ***********************/

extern int tapis_conv__tapis_init(void);
extern int tapis_conv__tapis(void);

#endif /*_TAPIS_CONV__TAPIS_H*/
